### ISSUE TITLE
Data restore failed

### ISSUE THREAD

**Issue by DownfallVision** [mathisdt/trackworktime#237] opened 2023-02-03 17:27 UTC
I have recently changed from a Samsung S9 to a Pixel 6a. When I've tried to transfer my TWT data, it app succeeds in restoring my preferences, but fails to restore my events.

When I first tried the restore, all three files were in the twt_backup folder, but it did not restore the events. So I delete the preferences and targets files and tried again with just the events and it failed. As far as I can tell I am doing everything correctly and it should work.

Log produced just now attached.
[2023-02-03-17-19-48.txt](https://github.com/mathisdt/trackworktime/files/10581193/2023-02-03-17-19-48.txt)

**Comment by mathisdt** [comment] 2023-02-04 12:40
There is one exception occurring multiple times:

```
j$.time.format.DateTimeParseException: Text '4' could not be parsed at index 0
	at j$.time.format.DateTimeFormatter.parseResolved0(SourceFile:0)
	at j$.time.format.DateTimeFormatter.parse(Unknown Source:5)
	at org.zephyrsoft.trackworktime.database.DAO.parseOffsetDateTime(DAO.java:800)
	at org.zephyrsoft.trackworktime.database.DAO.restoreEventsFromReader(DAO.java:776)
	at org.zephyrsoft.trackworktime.util.BackupUtil.lambda$doRestore$4(BackupUtil.java:101)
	...
```

After having a look at the code, I suspect that the backup file is corrupted. It is a simple CSV file which can also be opened in LibreOffice or Excel, so could you please make sure that the second column of the events file always contains a timestamp? The error message says that it found an entry there starting with `4` which currently is impossible for a timestamp. It should always start with `YYYY-MM-DD`. I'm pretty confident that the file can be imported after fixing this.

By the way, the restore always needs all three files. Please don't remove the two which  already worked, the data is re-imported together.

**Comment by DownfallVision** [comment] 2023-02-06 09:24
Thanks for getting back to me. I did actually try creating a new backup on the old device before posting here and it didn't fix it.

I've had a look and there are a few entries which don't have a timestamp in the second column. A quick look at these and most of them follow entries which look incomplete. It looks like for some reason some entries have split into two.

I'll fix that, restore with all three back up files and let you know how it goes.

**Comment by mathisdt** [comment] 2023-02-06 16:06
I would also be interested in any exceptions (including their stack traces) on your old device. Maybe there's still something bad happening which should be fixed. Could you have a look and attach the relevant parts of the log file to this issue?

**Comment by mathisdt** [comment] 2023-05-25 17:12
It's been more than 3 months now, I assume the problem is fixed. If not, feel free to comment and/or re-open!

**Closed by mathisdt** 2023-05-25 17:12 UTC
