### ISSUE TITLE
Multiple work locations

### ISSUE THREAD

**Issue by Heis** [mathisdt/trackworktime#54] opened 2019-01-15 15:02 UTC
Thanks for a nice app! It has potential to save me from 5 mins a day of unimportant work after a policy change at my employer.

I have an office job that is split between two locations. It would be nice to location track both of them as work time automatically. SSID-tracking will not be as reliable or accurate for me, but it will be a second best workaround.

**Comment by mathisdt** [comment] 2019-02-24 17:16
This is a duplicate of #3.

**Closed by mathisdt** 2019-02-24 17:16 UTC
Labels: duplicate
