### ISSUE TITLE
App crashes when deleting multible events

### ISSUE THREAD

**Issue by pappou99** [mathisdt/trackworktime#153] opened 2021-03-27 13:46 UTC
My setup is, that the app trackes automatic if it sees a specific Wifi-SSID. That produces many IN and OUT entrys.
When I then want to clean up the multible entrys, I mark them and hit the Trashbin.

Mostly (often, 4 of 5 times) the app crashes. Sometimes some entrys are notdeleted.

AppVer: 1.1.8
Os: Android 8.0.0 (Googlefree)

**Comment by mathisdt** [comment] 2021-03-27 14:08
Thanks for the report! I have good news for you: the crash when deleting multiple events at once should be fixed in 1.1.9 which is available from Google Play and Github already - sadly F-Droid takes even more time than Google for publishing the update.

For reference: [this commit](https://github.com/mathisdt/trackworktime/commit/f7e96f99fef712f3885c69146d078da5bdfd73ce) should have fixed it. At least I couldn't provoke the error after the fix - if it's not fixed for you in 1.1.9 please reopen this issue and also consider sending me your log file (via the menu item) so I can have a look at the stack trace which reveals the root cause.

**Closed by mathisdt** 2021-03-27 14:08 UTC
