### ISSUE TITLE
WiFi based tracking keeps disconnecting

### ISSUE THREAD

**Issue by berceanu** [mathisdt/trackworktime#29] opened 2018-01-11 14:06 UTC
Using `Android 8.0.0` on my `OnePlus 3` phone, I have enabled `Track by WiFi`, entered `SSID` of my Workplace network, and the event log is full of `IN`/`OUT` events every couple of minutes, even though the `SSID` never loses signal.

**Comment by mathisdt** [comment] 2018-01-11 19:58
Could you please try to disable the battery optimization for TWT in the settings? Maybe Android causes the `IN`/`OUT` events by manipulating the app for power saving.

These screenshots may help you get to the right place (sadly the option is not very obvious):
[screenshot 1](https://user-images.githubusercontent.com/1932462/34844263-30dfa990-f711-11e7-900c-7266da9c7b27.png)
[screenshot 2](https://user-images.githubusercontent.com/1932462/34844277-3cb0a47c-f711-11e7-8789-1dfa2e1646e6.png)
[screenshot 3](https://user-images.githubusercontent.com/1932462/34844282-4069f776-f711-11e7-9116-b54ec7b854fb.png)
[screenshot 4](https://user-images.githubusercontent.com/1932462/34844284-43f0b90c-f711-11e7-9791-34e455a04df8.png)
[screenshot 5](https://user-images.githubusercontent.com/1932462/34844291-48e8fbae-f711-11e7-862c-0cda03458a34.png)
[screenshot 6](https://user-images.githubusercontent.com/1932462/34844299-4c3c09c2-f711-11e7-913a-ce7c52d92f1a.png)
[screenshot 7](https://user-images.githubusercontent.com/1932462/34844303-4fae2aa4-f711-11e7-934f-6338ffa30cee.png)

**Comment by berceanu** [comment] 2018-01-12 10:53
Thank you, I followed the instructions in the screenshots but unfortunately the problem persists. Here is a screenshot showing the events for today.

![screenshot jan 12 2018 12_48_36 pm](https://user-images.githubusercontent.com/4405658/34871776-834e4afc-f797-11e7-84e7-3def57301d12.jpg)

**Comment by mathisdt** [comment] 2018-01-12 12:40
It seems that Android Oreo creates some extra work for developers of location-aware apps which are not in the foreground all the time - see https://developer.android.com/about/versions/oreo/background-location-limits.html

I honestly don't know when I will have the time to look into this new behaviour of Android.

**Comment by mathisdt** [comment] 2018-01-12 12:42
@PRosenb, do you know how to get around this obstacle?

**Comment by PRosenb** [comment] 2018-01-13 22:21
@mathisdt, I see this issue on my device too and will do some tests to find out if it can be resolved without too much effort.

**Comment by mathisdt** [comment] 2018-06-13 18:28
@berceanu: I should have resolved this issue with the fix for #37. Could you please re-test using the newly released version 1.0.3?

**Comment by WildOrangutan** [comment] 2018-06-16 21:42
This issue still persists in 1.0.3

**Comment by WildOrangutan** [comment] 2018-06-16 22:42
Something that may help you to figure out what's going on. I'll try to fiddle around a bit, but can't make any promises.

#### Reproduce
- emulator API 26 (or later, dunno I've used this one)

1. Start the app and set it up
2. Press power button (Ctrl+P) to put it to ?sleep? mode
3. Should start disconnecting every few minutes

#### Logcat
- https://pastebin.com/v3gNyfPG

**Comment by mathisdt** [comment] 2018-06-21 20:12
Using your description I finally could observe the problem myself ([log](https://github.com/mathisdt/trackworktime/files/2125185/log.txt)). This is good - but I'm still not sure when I will have the time to fix it.

**Comment by WildOrangutan** [comment] 2018-11-07 18:31
Just fyi, I'm cooking up a fix for this issue. Basically using [this](https://developer.android.com/guide/topics/connectivity/wifi-scan) implementation seems to solve this problem. Checking `WifiManager.startScan()` return value and more importantly `WifiManager.EXTRA_RESULTS_UPDATED` and only then checking `WifiManager.getScanResults()` does the job.

**Comment by WildOrangutan** [comment] 2018-11-14 19:31
@mathisdt Let me know what you think about my fix 21615f3 . I've been testing it on my phone for about a week without any issues.

If you want, I can also include basic functional tests for new functionality. I've played around a bit and almost have them made in Mockito + Junit4.

**Comment by mathisdt** [comment] 2018-11-14 20:07
@WildOrangutan Great to hear of your progress! I have two questions about your change: 
1. Major: Could it be done without requiring CHANGE_WIFI_STATE permission? Requesting this might be seen as intrusive, so if possible, I'd very much like to go without it.
2. Minor: Can we please (a) use blocks in if-else statements to ensure consistency and (b) remove prefixes like "m" from instance variable names? (I know, then we have to use a "this." qualifier to address the right variable, but for my understanding prefixes make the code more difficult to read.)

**Comment by WildOrangutan** [comment] 2018-11-14 21:20
Even tough documentation says otherwise, CHANGE_WIFI_STATE is a must have. I'd say due to build tools version already on 28. App crashes otherwise.

**Comment by WildOrangutan** [comment] 2018-11-14 22:29
One more idea on permission thingy (sorry for spamming). If you really want to avoid it, I guess you could omit wifiManager.startScan() and only listen when scan results update. Similarly like it's working on master atm. Tough relying only on other services to initiate scans is a bit optimistic imho.

**Comment by WildOrangutan** [comment] 2019-09-28 18:09
@mathisdt I suggest closing this (and possibly similar) issues. Last fix seems to be working reliably for me.

**Comment by mathisdt** [comment] 2019-09-29 16:03
Thanks @WildOrangutan. Seems to work. :smiley:

**Closed by mathisdt** 2019-09-29 16:03 UTC
