### ISSUE TITLE
Popup asking for storage permission pops up every time

### ISSUE THREAD

**Issue by nikolockenvitz** [mathisdt/trackworktime#164] opened 2021-04-21 12:27 UTC
I did not grant the storage permission in Android (I don't need this feature as I already have regularly backups of the data). Now, every time the main activity gets focus, the app shows a popup asking for storage permission. It's somehow annoying to click that away every time. I would therefore ask you, to allow disabling that popup. It's advertised as an optional feature in the popup and doesn't seem to be necessary so I don't see a need to display this popup a hundreds of times.

https://github.com/mathisdt/trackworktime/blob/41e4a700d4d193171cb4ed1a536ee80cafa31c08/app/src/main/java/org/zephyrsoft/trackworktime/WorkTimeTrackerActivity.java#L334-L340

**Comment by mathisdt** [comment] 2021-04-22 19:51
I can understand that you don't like denying the same permission request over and over. The problem is that the storage part of the app needs a general overhaul because there are multiple things stored on external storage currently (also see #139):

1. up to 3 log files (rotated daily)
2. automatic backups, generated daily (independent of user activity)
3. manually triggered backups

While all files could also be created on app-internal storage, this would be bad for the user - this storage is cleared when the app is uninstalled, and thus any backup would vanish when a user would delete and reinstall the app. I suppose this is not what the user expects. Someone (maybe I) has to figure out how the files can be saved via another way than simply on external storage (for which the requested permission is necessary) because the Play store will force updates coming in later this year to target API 30, which in turn will drop writing ability on external storage. After this is done, your problem will also be gone - if you want, you are invited to come up with a solution yourself!

----

Just out of curiosity: how do you back up TWT's data without grabbing the files the app would write? Do you use Titanium Backup to fetch the database contents directly?

**Comment by nikolockenvitz** [comment] 2021-04-22 20:02
It's not the Android permission request that pops up over and over again (this can be disabled easily) but the popup of the app. For that I would ask you to implement a way of stopping that popup, e.g. add a "don't show this again"-button.

I transfer the data manually on a regularly basis into a local spreadsheet for more advanced analytics.

**Comment by mathisdt** [comment] 2021-07-14 17:57
Sorry for getting back so late! I'm optimistic that when #139 is done, this should be obsolete (because there won't be any permission which has to be granted), but sadly I don't have much time at the moment.

**Comment by mathisdt** [comment] 2021-11-26 15:24
Shortly, version 1.1.10 will be released, and this version won't ask for storage permission on every usage.

With the new version, you will be asked for one directory (which can be located anywhere on your device or on an external SD card), and the app will have access only to this directory. It's also possible to create a directory for that purpose only. 

It's necessary to have such a space on shared storage because the app generates some files (reports, backups) which wouldn't make sense inside the app's internal data directory - this (internal) data is deleted on uninstallation of the app. I think it's not good to have the backups erased only because you reinstall the app (or accidentally uninstall it).

The app will continue to work mostly even if you don't grant any storage directory, but then some features won't work (because they need the storage). Also, **the automatic backup mechanism won't do anything** (this is meant for the case your device's screen gets cracked and you can only copy files from it via cable before it dies completely - the automatic backup files can be restored in another device if you put them into the directory you grant to the app there).

**Closed by mathisdt** 2021-11-26 15:24 UTC
Labels: obsolete

**Comment by nikolockenvitz** [comment] 2021-11-26 15:37
Sounds good. Thanks @mathisdt
